/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./public/stylesheets/**/*.{html,js}", "./app/views/**/*"],
  darkMode: "media",
  theme: {
    extend: {
      colors: {
        primary: {
          special: "#ffbc68",
          special2: "#00a8a0",
          dark: "#303b4a",
          light: "#fcfafb",
          semiLight: "#a7a9be",
        },
      },
    },
    fontFamily: {
      body: [
        "Lato",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      sans: [
        "Lato",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
    },
  },
  plugins: [],
};
